#!/bin/bash

# Install into git hooks folder with the following command
# ln -s `pwd`/post-commit ../.git/hooks/post-commit
#
# This is to automatically create a tag if a new version is added into notes.md
# Format of the tag is v.<version>
# The first line of notes.md is parsed based on the following pattern
# `<version>`<anything else>
#
# .git/config is recommended to update according to below to push local tags with git push
# [remote "origin"]
#         url = ...
#         fetch = ...
#         push = +refs/heads/*
#         push = +refs/tags/*

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if [[ ! $BRANCH_NAME == master ]]
then
  exit 0
fi

LINE=$(head -n 1 notes.md)
REGEX='`(.*)`.*'
if [[ $LINE =~ $REGEX ]]
then
   VERSION=${BASH_REMATCH[1]}
   TAG="v.$VERSION"
   if ! git rev-parse $TAG >/dev/null 2>&1
   then
       git tag $TAG
   fi
fi
