# This is a basic workflow to help you get started with Actions

name: KDB Studio build (Java 8)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-kdb-studio:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Project checkout
      uses: actions/checkout@v2

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build KDB Studio (with gradle)
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: check install
    - name: Integration Test
      run: ./test.sh
    - name: Show workspace
      run: find
    - name: Make release archive
      run: cd build/install; zip -r studio *
    - name: Upload release
      if: github.event_name == 'push'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Build"
        files: |
          build/install/studio.zip
